# Generated by Django 3.1.2 on 2020-10-20 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(days=5), help_text='use this field when you need to have information  about bouquet fresh time', null=True),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='discount_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='could_use_in_bouquet',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='wiki',
            field=models.URLField(default='https://www.wiki.ru', null=True, unique_for_date='delivered_at'),
        ),
    ]
